name: Fetch Total Amount and Commit to Repo

permissions:
  contents: write

on:
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch and Process Total Amount
        id: fetch-amount
        env:
          API_URL: 'https://frontend-api.kentaa.nl/actions/cVPiLcz9Nh81'
        run: |
          # Fetch data with error handling
          response=$(curl -f --silent --location "$API_URL" \
            --header 'accept: application/json' \
            --header 'x-locale: en' \
            --header 'x-site-id: aoEcWgKEz2NS')
          
          # Validate and extract amount
          total_amount=$(echo "$response" | jq -e '.data.total_amount | tonumber')
          
          if [ $? -ne 0 ]; then
            echo "Error: Unable to extract total amount from API response"
            exit 1
          fi
          
          # Create amount.json with extracted value
          echo "{ \"number\": $total_amount }" > amount.json
          
          # Set output for potential debugging
          echo "total_amount=$total_amount" >> "$GITHUB_OUTPUT"

      - name: Prepare Git Configuration
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if there are changes
          if ! git diff --quiet --exit-code -- amount.json; then
            git add amount.json
            git commit -m "Update amount.json: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi