name: Fetch Total Amount and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *' # Exécute chaque heure
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch data from API
        run: |
          RESPONSE=$(curl --silent --location 'https://frontend-api.kentaa.nl/actions/cVPiLcz9Nh81' \
            --header 'accept: application/json' \
            --header 'x-locale: en' \
            --header 'x-site-id: aoEcWgKEz2NS')
          TOTAL_AMOUNT=$(echo $RESPONSE | jq -r '.data.total_amount | tonumber')
          mkdir -p public
          echo "{ \"number\": $TOTAL_AMOUNT }" > public/amount.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_SECRET }}
          publish_dir: ./public
