name: Fetch Total Amount

on:
  schedule:
    - cron: '0 * * * *' # Exécute chaque heure
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch data from API
        run: |
          RESPONSE=$(curl --silent --location 'https://frontend-api.kentaa.nl/actions/cVPiLcz9Nh81' \
            --header 'accept: application/json' \
            --header 'x-locale: en' \
            --header 'x-site-id: aoEcWgKEz2NS')
          TOTAL_AMOUNT=$(echo $RESPONSE | jq -r '.data.total_amount | tonumber')
          echo "{ \"number\": $TOTAL_AMOUNT }" > amount.json

      - name: Upload amount.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: amount-data
          path: amount.json
          retention-days: 30
