name: Fetch Total Amount and Commit to Repo

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *' # Exécute chaque heure
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch data from API
        run: |
          RESPONSE=$(curl --silent --location 'https://frontend-api.kentaa.nl/actions/cVPiLcz9Nh81' \
            --header 'accept: application/json' \
            --header 'x-locale: en' \
            --header 'x-site-id: aoEcWgKEz2NS')
          TOTAL_AMOUNT=$(echo $RESPONSE | jq -r '.data.total_amount | tonumber')
          echo "{ \"number\": $TOTAL_AMOUNT }" > amount.json

      - name: Commit and push amount.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase
          git add amount.json
          git commit -m "Update amount.json with latest total_amount" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main